# Generated by Django 2.2.6 on 2019-10-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_members', models.PositiveSmallIntegerField()),
                ('deadline', models.DateTimeField()),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alert_frequency', models.CharField(max_length=16)),
                ('apply_interest', models.BooleanField()),
                ('interest_rate', models.FloatField()),
                ('completed', models.BooleanField()),
                ('expected_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField()),
                ('average_rating', models.FloatField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
