# Generated by Django 2.2.6 on 2019-11-01 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='expected_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('completed', models.BooleanField()),
                ('completed_date', models.DateTimeField()),
                ('lender_confirm', models.BooleanField()),
                ('borrower_confirm', models.BooleanField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_transaction', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lended_transaction', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan')),
            ],
        ),
    ]
