# Generated by Django 2.2 on 2019-12-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20191213_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='num_completed_tx',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
