# Generated by Django 2.2.8 on 2019-12-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20191213_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
