# Generated by Django 2.2 on 2019-12-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loan_progress_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='num_completed_tx',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='progress_rate',
        ),
    ]
