# Generated by Django 2.2 on 2019-12-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20191213_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='progress_rate',
            field=models.FloatField(default=1),
        ),
    ]
