# Generated by Django 2.2 on 2019-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_loan_progress_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='progress_rate',
            field=models.FloatField(default=0),
        ),
    ]
