# Generated by Django 2.2.8 on 2019-12-14 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('kakao_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('twilio_msg', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(default=0)),
                ('profile_img', models.ImageField(blank=True, upload_to='profile_img')),
            ],
        ),
    ]
