# Generated by Django 2.2.6 on 2019-11-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191031_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='kakao_id',
            new_name='kakaoId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
