# Generated by Django 2.2.6 on 2019-10-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191012_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
