# Generated by Django 2.2.6 on 2019-11-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191102_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='kakaoId',
            new_name='kakao_id',
        ),
    ]
