# Generated by Django 2.2.6 on 2019-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191203_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
