# Generated by Django 2.2.6 on 2019-12-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191203_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
