# Generated by Django 2.2.7 on 2019-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191203_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/default_image.jpg', upload_to=''),
        ),
    ]
