# Generated by Django 2.2 on 2019-12-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191207_0001'),
        ('account', '0007_auto_20191209_0629'),
    ]

    operations = [
    ]
